name: Deploy Frontend
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .  # build image 
      - run: docker run -e CI=true cygnetops/react-test npm test  # test container
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          # aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          # aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_access_key: AWS_ACCESS_KEY
          aws_secret_key: AWS_SECRET_KEY
          application_name: docker-react  # see Elastic Beanstalk
          environment_name: Docker-react-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-3-562786867924
          region: ap-northeast-3
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip